/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#bda1ff",
        "primary": "#96f8ff",
        "on-primary-fixed-variant": "#006065",
        "secondary": "#00fe66",
        "secondary-fixed-dim": "#00ee5f",
        "primary-fixed-dim": "#00e2ed",
        "on-surface-variant": "#acaab1",
        "on-error": "#490006",
        "tertiary-container": "#7000ff",
        "background": "#0e0e13",
        "on-tertiary-container": "#f8f1ff",
        "error-dim": "#d7383b",
        "surface-bright": "#2c2b33",
        "surface-container": "#19191f",
        "tertiary-fixed-dim": "#b190ff",
        "error-container": "#9f0519",
        "tertiary-dim": "#874cff",
        "on-tertiary": "#290067",
        "surface-dim": "#0e0e13",
        "inverse-primary": "#006a6f",
        "inverse-on-surface": "#55545b",
        "on-primary": "#005f64",
        "surface-container-lowest": "#000000",
        "error": "#ff716c",
        "surface-variant": "#25252d",
        "secondary-fixed": "#00fe66",
        "on-secondary-fixed": "#004616",
        "on-secondary-fixed-variant": "#006624",
        "surface-container-highest": "#25252d",
        "outline": "#76747b",
        "tertiary": "#ac89ff",
        "surface-container-low": "#131319",
        "primary-fixed": "#00f1fd",
        "on-tertiary-fixed": "#1f0052",
        "on-secondary-container": "#e5ffe0",
        "outline-variant": "#48474d",
        "on-error-container": "#ffa8a3",
        "on-primary-container": "#00565a",
        "secondary-dim": "#00ee5f",
        "on-background": "#f9f5fd",
        "secondary-container": "#006e27",
        "inverse-surface": "#fcf8ff",
        "on-secondary": "#005b1f",
        "surface": "#0e0e13",
        "primary-dim": "#00e2ed",
        "surface-tint": "#96f8ff",
        "on-tertiary-fixed-variant": "#4700a7",
        "on-primary-fixed": "#004145",
        "surface-container-high": "#1f1f26",
        "on-surface": "#f9f5fd",
        "primary-container": "#00f1fd"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Space Grotesk", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
